=== AbdullahHinnawi/AvoimetRajapinnat/XML/Tasks.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
        <!ATTLIST task taskID ID #REQUIRED>
        <!ELEMENT tasks (task*)>
        <!ELEMENT name (#PCDATA)>  <!-- element declaration -->
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT yes (#PCDATA)>
        <!ELEMENT no (#PCDATA)>
        <!ELEMENT completed (yes | no)>
        <!ELEMENT moreInfo (#PCDATA)>
        <!ELEMENT task (name,date,time,completed,moreInfo?)>

=== AbdullahHinnawi/AvoimetRajapinnat/XML/Tasks.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE tasks SYSTEM "Tasks.dtd">
<tasks>
    <task taskID="A1234">
        <name>Task 1</name>
        <date>2020-10-24</date>
        <time>13:20:00</time>
        <completed><no/></completed>
        <moreInfo>For more info about this task, you can check....</moreInfo>
    </task>
</tasks>
